# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MovieDB' do
  use_frameworks!

  # Pods for MovieDB
  pod 'SwiftLint', '0.39.1'
  pod 'SwiftGen', '6.0'
  pod 'KeychainAccess', '4.1.0'

end

target 'MovieDBAPI' do
  use_frameworks!

  # Pods for MovieDBAPI

end

target 'MovieDBStorage' do
  use_frameworks!

  # Pods for MovieDBAPI
  pod 'RealmSwift', '4.3.2'

end
