# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MovieDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDB
  pod 'SwiftLint', '0.39.1'
  pod 'SwiftGen', '6.0'

end
